language: rust
sudo: false

matrix:
  include:

  # tests pass
  - rust: nightly-2018-07-18
    script:
    - cargo test --all --locked
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check
    env: RUST_BACKTRACE=1
